name: Pumpkin
description: A simple plugin to simplify the development of spigot plugins.
author: Finn
version: '${version}'
main: org.bukkit.plugin.java.JavaPlugin
api-version: 1.18
load: STARTUP
commands:
  pumpkin:
    description: PumpkinAPI is a simple plugin to simplify development of spigot plugins.
    aliases: pumpkinapi